### PR TITLE
Remove inline contact form

### LINKED ISSUE #98: Remove inline newsletter sign up
Confirm whether the embedded newsletter sign up is easily broken by changes to the form on the Mailchimp side. Consider moving to an API solution, which would isolate us from changes (most, maybe not changes to audience IDs) made in the UI and let us fully control the styling/experience.

Arose as a result of #25 
See also #24

### PR DESCRIPTION
**Pull request by pgfisico**
Resolves #98

### CODE REVIEW

File: src/pages/sponsors.js [hunk 1]
```diff
@@ -38,15 +34,8 @@ const SponsorsPage = () => {
...
         <Row>
-          <Col
-            xs={12}
-            sm={12}
-            md={3}
-            lg={3}
-            xl={3}
-            className='mr-md-5 mr-lg-5 mr-xl-5 mb-5'
-          >
-            <FontAwesomeIcon icon={faHandSpock} size={'10x'} />
```
Comment (pgfisico) [inline src/pages/sponsors.js:49]: Difficult to get a nice layout with so little text so removed the icon. We can address content and layout later when off of Bootstrap.

File: src/pages/sponsors.js [hunk 2]
```diff
@@ -63,23 +52,8 @@ const SponsorsPage = () => {
...
-
-      <Container
-        fluid={true}
-        className='mt-5 px-lg-5 px-xl-5 px-md-5 px-sm-1 px-xs-1'
-      >
         <Row>
-          <Col xs={12} sm={12} md={6} lg={6} xl={6} className='pb-5'>
-            <img
-              src={flickr_34139744040_dd7101632a_h}
-              alt='pitching for a sponsorship'
```
Comment (pgfisico) [inline src/pages/sponsors.js:78]: Incorrect alt text
